### PR TITLE
now world is animated in GameFragment;

### PR DESCRIPTION
**Pull request by fizarum**
added method on lifeform moved in LifeformChangeListener; 
removed relativeLayout dependency from Animal class; 
fixed issue when game continues working in background; code cleanup;

### CODE REVIEW

**Comment by pushapp** [comment]
Sorry I haven't gotten a chance to work on it this week, been swamped busy. I'll be back to it after this weekend! Stoked to see all the updates

**Comment by fizarum** [comment]
no problem ;)

**Comment by fizarum** [comment]
one issue found during testing - game became pretty slow when it has a lot of lifeforms - I'll check what I can do with that. Initial idea is to rework that layout to canvas. Anyway will start work on that part as soon as I complete game fragment

**Comment by pushapp** [comment]
Yeah I noticed that. What about running everything async in between
updates? Doesn't really address the problem though. Maybe putting a limit
to the number of lifeforms added each turn to prevent it going exponential.

**Comment by fizarum** [comment]
Android doesn't allow to update UI from non-UI thread, so.
Limit can postpone the problem but won't solve it - android devices can be pretty slow, so it can be problematic to calculate these numbers...
Current solution (with image view for each lifeform) is too heavy to draw on screen.

**Pull request merged**
