### PR TITLE
added scrollable area in dialog view for extra ui elements;

### PR DESCRIPTION
**Pull request by fizarum**
fixed issue with not showed "Add & Cancel" buttons for animals; 
now, on switching between lifeform types ui resets to default view; 
fixed issue with incorrect calculation Darwin points on lifeform type change; 
added some debug logs;

### CODE REVIEW

**Review by pushapp — APPROVED** [review]
looks great!

**Comment by pushapp** [comment]
I think when I pushed my latest, it removed this PR cause I didnt merge it properly. New to working with someone so I might have botched it. Resend it when you have a chance!

**Comment by fizarum** [comment]
no problem, actually this PR already contains all missed fixes, next time I'll try to make one-commit PR

**Comment by fizarum** [comment]
hm.. after fetching latest changes from master still can't find changes from this PR.. ok wait for third try :D

**Comment by pushapp** [comment]
Yeah I was working with the version before your PR3. Then accidentally
pushed it without merging your PR so it erased it. You should still have it
on your fork though right? To just make another PR?

**Comment by fizarum** [comment]
Yup, I'll add lost changes one more time in next PR, no problem)

**Pull request merged**
