### PR TITLE
bugfixes & improvements

### PR DESCRIPTION
**Pull request by fizarum**
bumped up min android version to 24 for newer stream API + next improvements in sharedPrefs encryption;
fixed bug in animal creation because of wrong parent layout type;
added warning message when user has low Darwin points;
now map clears correctly when new world is created;
world updating moved to World class;
cleaned up World class;

### CODE REVIEW

**Comment by pushapp** [comment]
Looks great! Hey Michael, do you have much experience with Jetpack Compose? Do you know if its worth switching to for this project? I've never used it

**Comment by fizarum** [comment]
Yup, I have some. Its pretty young but good feature and simplifies writing UI. But there are some requirements:
- we have to switch to kotlin (what is very welcome! - much, much better that java);
- use mvvm pattern (we actually moving toward this pattern, by removing everything from activity);

I've started to cleanup MainActivity, but it requires some time, plus we have some coupling between models and UI, for example Lifeform knows about Context and ImageView.
At this moment I can propose to start using kotlin - it will be a big app improvement

**Comment by fizarum** [comment]
+ to this discussion, can we organize some communication channel? We can use existing one, but it will be tedious - to create new PR to discuss some things :)

**Comment by pushapp** [comment]
I'm up for it. I have zero experience with kotlin but id love to learn if
you walk me through the switch

**Comment by fizarum** [comment]
sure, no problem :)

**Pull request merged**
